sudo: required
services:
  - docker

before_install:
  - docker build -t sunilkumarhr5593/docker-react -f Dockerfile.dev .

script:
  - docker run sunilkumarhr5593/docker-react npm run test -- --coverage